name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Set Minikube context
      run: minikube update-context
    - name: Apply Kubernetes manifests to Minikube
      run: kubectl apply -f kubernetes/deployment.yaml -f kubernetes/service.yaml





# name: CD Pipeline

# on:
#     workflow_run:
#       workflows: ["CI Pipeline"]
#       types:
#         - completed

# jobs:

#   build:

#     runs-on: self-hosted

#     steps:
#     - name: Pull docker image
#       run: sudo docker pull nipun2221/weather-app:latest
#     - name: Delete old docker container
#       run: sudo docker rm -f weather-app-container || true
#     - name: Run the Docker container
#       run: sudo docker run -d -p 5000:5000 --name weather-app-container nipun2221/weather-app:latest