name: CICD

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v3
            - name: Authenticate Docker
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                docker build --build-arg api-key=${{ secrets.WEATHER_API_KEY }} -t nipun2221/weather-api .
                docker push nipun2221/weather-api:latest

    deploy:
        runs-on: [aws-ec2]
        needs: build
        steps:
            - name: Pull image from docker hub
              run: docker pull nipun2221/weather-api:latest
            - name: Delete old container
              run: docker rm -f weather-api-container
            - name: Run docker container
              run: docker run -d -p 5000:5000 --name weather-api-container nipun2221/weather-api
