name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login dockerhub
      env: 
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
         API_KEY: ${{ secrets.API_KEY }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: | 
        docker build --build-arg api_key=$API_KEY -t weather-app:latest .
        docker images
    - name: Push to dockerhub
      run: | 
        docker push nipun2221/weather-app:latest
        docker images
